### ISSUE TITLE
ارور ssl

### ISSUE THREAD

**Issue by Hoseinkhalaj1** [Real-kia/kia-marzban-admin#1]
متاسفانه ارور ssl دارم و ربات ران نمیشه
تانل هست پنلم و ssl فعاله

**Comment by Real-kia** [comment]
درود
ربات رو کجا ران میکنید؟
این کامند رو بزنین و نتیجه رو بفرسیتن
journalctl -u kiamarzbanbot.service --no-pager --lines=100

**Comment by mohamadaz** [comment]
ربات روی سرور اصلی هست
`-- Logs begin at Fri 2024-02-09 20:56:50 UTC, end at Mon 2024-02-19 12:17:59 UTC. --
Feb 18 09:13:44 mrz python3[985878]: During handling of the above exception, another exception occurred:
Feb 18 09:13:44 mrz python3[985878]: Traceback (most recent call last):
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 486, in send
Feb 18 09:13:44 mrz python3[985878]:     resp = conn.urlopen(
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 720, in urlopen
Feb 18 09:13:44 mrz python3[985878]:     retries = retries.increment(
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
Feb 18 09:13:44 mrz python3[985878]:     raise MaxRetryError(_pool, url, error or ResponseError(cause))
Feb 18 09:13:44 mrz python3[985878]: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='IP', port=443): Max retries exceeded with url: /api/admin/token (Caused by SSLError(SSLCertVerificationError("hostname 'IP' doesn't match 'sub.domain.com'")))
Feb 18 09:13:44 mrz python3[985878]: During handling of the above exception, another exception occurred:
Feb 18 09:13:44 mrz python3[985878]: Traceback (most recent call last):
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
Feb 18 09:13:44 mrz python3[985878]:     for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
Feb 18 09:13:44 mrz python3[985878]:     return await asyncio.gather(*tasks)
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 117, in notify
Feb 18 09:13:44 mrz python3[985878]:     response = await handler_obj.handler(*args, **partial_data)
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
Feb 18 09:13:44 mrz python3[985878]:     return await self.callback_query_handlers.notify(update.callback_query)
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 117, in notify
Feb 18 09:13:44 mrz python3[985878]:     response = await handler_obj.handler(*args, **partial_data)
Feb 18 09:13:44 mrz python3[985878]:   File "/root/kia-marzban-admin/handlers/template.py", line 55, in template_manage
Feb 18 09:13:44 mrz python3[985878]:     template_list = get_templates()
Feb 18 09:13:44 mrz python3[985878]:   File "/root/kia-marzban-admin/utils/panel.py", line 22, in get_templates
Feb 18 09:13:44 mrz python3[985878]:     token = login(panel_username, panel_pass)
Feb 18 09:13:44 mrz python3[985878]:   File "/root/kia-marzban-admin/utils/login.py", line 24, in login
Feb 18 09:13:44 mrz python3[985878]:     response = requests.post(url=login_url, data=data)
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 115, in post
Feb 18 09:13:44 mrz python3[985878]:     return request("post", url, data=data, json=json, **kwargs)
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 59, in request
Feb 18 09:13:44 mrz python3[985878]:     return session.request(method=method, url=url, **kwargs)
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 589, in request
Feb 18 09:13:44 mrz python3[985878]:     resp = self.send(prep, **send_kwargs)
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 703, in send
Feb 18 09:13:44 mrz python3[985878]:     r = adapter.send(request, **kwargs)
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 517, in send
Feb 18 09:13:44 mrz python3[985878]:     raise SSLError(e, request=request)
Feb 18 09:13:44 mrz python3[985878]: requests.exceptions.SSLError: HTTPSConnectionPool(host='IP', port=443): Max retries exceeded with url: /api/admin/token (Caused by SSLError(SSLCertVerificationError("hostname 'IP' doesn't match 'sub.domain.com'")))
Feb 19 12:11:35 mrz systemd[1]: Stopping Kia Marzban Bot Service...
Feb 19 12:11:35 mrz systemd[1]: kiamarzbanbot.service: Succeeded.
Feb 19 12:11:35 mrz systemd[1]: Stopped Kia Marzban Bot Service.
Feb 19 12:17:09 mrz systemd[1]: Started Kia Marzban Bot Service.
Feb 19 12:17:37 mrz python3[1657344]: Task exception was never retrieved
Feb 19 12:17:37 mrz python3[1657344]: future: <Task finished name='Task-16' coro=<Dispatcher._process_polling_updates() done, defined at /usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py:407> exception=SSLError(MaxRetryError("HTTPSConnectionPool(host='sub.domain.com', port=443): Max retries exceeded with url: /api/admin/token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))"))>
Feb 19 12:17:37 mrz python3[1657344]: Traceback (most recent call last):
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 666, in urlopen
Feb 19 12:17:37 mrz python3[1657344]:     httplib_response = self._make_request(
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
Feb 19 12:17:37 mrz python3[1657344]:     self._validate_conn(conn)
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1001, in _validate_conn
Feb 19 12:17:37 mrz python3[1657344]:     conn.connect()
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 366, in connect
Feb 19 12:17:37 mrz python3[1657344]:     self.sock = ssl_wrap_socket(
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
Feb 19 12:17:37 mrz python3[1657344]:     return context.wrap_socket(sock, server_hostname=server_hostname)
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
Feb 19 12:17:37 mrz python3[1657344]:     return self.sslsocket_class._create(
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/lib/python3.8/ssl.py", line 1069, in _create
Feb 19 12:17:37 mrz python3[1657344]:     self.do_handshake()
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/lib/python3.8/ssl.py", line 1338, in do_handshake
Feb 19 12:17:37 mrz python3[1657344]:     self._sslobj.do_handshake()
Feb 19 12:17:37 mrz python3[1657344]: ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)
Feb 19 12:17:37 mrz python3[1657344]: During handling of the above exception, another exception occurred:
Feb 19 12:17:37 mrz python3[1657344]: Traceback (most recent call last):
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 486, in send
Feb 19 12:17:37 mrz python3[1657344]:     resp = conn.urlopen(
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 720, in urlopen
Feb 19 12:17:37 mrz python3[1657344]:     retries = retries.increment(
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
Feb 19 12:17:37 mrz python3[1657344]:     raise MaxRetryError(_pool, url, error or ResponseError(cause))
Feb 19 12:17:37 mrz python3[1657344]: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sub.domain.com', port=443): Max retries exceeded with url: /api/admin/token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
Feb 19 12:17:37 mrz python3[1657344]: During handling of the above exception, another exception occurred:
Feb 19 12:17:37 mrz python3[1657344]: Traceback (most recent call last):
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
Feb 19 12:17:37 mrz python3[1657344]:     for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
Feb 19 12:17:37 mrz python3[1657344]:     return await asyncio.gather(*tasks)
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 117, in notify
Feb 19 12:17:37 mrz python3[1657344]:     response = await handler_obj.handler(*args, **partial_data)
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
Feb 19 12:17:37 mrz python3[1657344]:     return await self.callback_query_handlers.notify(update.callback_query)
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 117, in notify
Feb 19 12:17:37 mrz python3[1657344]:     response = await handler_obj.handler(*args, **partial_data)
Feb 19 12:17:37 mrz python3[1657344]:   File "/root/kia-marzban-admin/handlers/template.py", line 55, in template_manage
Feb 19 12:17:37 mrz python3[1657344]:     template_list = get_templates()
Feb 19 12:17:37 mrz python3[1657344]:   File "/root/kia-marzban-admin/utils/panel.py", line 22, in get_templates
Feb 19 12:17:37 mrz python3[1657344]:     token = login(panel_username, panel_pass)
Feb 19 12:17:37 mrz python3[1657344]:   File "/root/kia-marzban-admin/utils/login.py", line 24, in login
Feb 19 12:17:37 mrz python3[1657344]:     response = requests.post(url=login_url, data=data)
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 115, in post
Feb 19 12:17:37 mrz python3[1657344]:     return request("post", url, data=data, json=json, **kwargs)
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 59, in request
Feb 19 12:17:37 mrz python3[1657344]:     return session.request(method=method, url=url, **kwargs)
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 589, in request
Feb 19 12:17:37 mrz python3[1657344]:     resp = self.send(prep, **send_kwargs)
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 703, in send
Feb 19 12:17:37 mrz python3[1657344]:     r = adapter.send(request, **kwargs)
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 517, in send
Feb 19 12:17:37 mrz python3[1657344]:     raise SSLError(e, request=request)
Feb 19 12:17:37 mrz python3[1657344]: requests.exceptions.SSLError: HTTPSConnectionPool(host='sub.domain.com', port=443): Max retries exceeded with url: /api/admin/token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))`

تا جایی که متوجه شدم چون تانل هستم و ایپی سرور با ایپی دامین متفاوت هست این ارور رو دارم

**Comment by Hoseinkhalaj1** [comment]
ربات رو سرور اصلی هست

-- Logs begin at Fri 2024-02-09 20:56:50 UTC, end at Mon 2024-02-19 12:17:59 UTC. --
Feb 18 09:13:44 mrz python3[985878]: During handling of the above exception, another exception occurred:
Feb 18 09:13:44 mrz python3[985878]: Traceback (most recent call last):
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 486, in send
Feb 18 09:13:44 mrz python3[985878]:     resp = conn.urlopen(
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 720, in urlopen
Feb 18 09:13:44 mrz python3[985878]:     retries = retries.increment(
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
Feb 18 09:13:44 mrz python3[985878]:     raise MaxRetryError(_pool, url, error or ResponseError(cause))
Feb 18 09:13:44 mrz python3[985878]: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='IP', port=443): Max retries exceeded with url: /api/admin/token (Caused by SSLError(SSLCertVerificationError("hostname 'IP' doesn't match 'sub.domain.com'")))
Feb 18 09:13:44 mrz python3[985878]: During handling of the above exception, another exception occurred:
Feb 18 09:13:44 mrz python3[985878]: Traceback (most recent call last):
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
Feb 18 09:13:44 mrz python3[985878]:     for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
Feb 18 09:13:44 mrz python3[985878]:     return await asyncio.gather(*tasks)
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 117, in notify
Feb 18 09:13:44 mrz python3[985878]:     response = await handler_obj.handler(*args, **partial_data)
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
Feb 18 09:13:44 mrz python3[985878]:     return await self.callback_query_handlers.notify(update.callback_query)
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 117, in notify
Feb 18 09:13:44 mrz python3[985878]:     response = await handler_obj.handler(*args, **partial_data)
Feb 18 09:13:44 mrz python3[985878]:   File "/root/kia-marzban-admin/handlers/template.py", line 55, in template_manage
Feb 18 09:13:44 mrz python3[985878]:     template_list = get_templates()
Feb 18 09:13:44 mrz python3[985878]:   File "/root/kia-marzban-admin/utils/panel.py", line 22, in get_templates
Feb 18 09:13:44 mrz python3[985878]:     token = login(panel_username, panel_pass)
Feb 18 09:13:44 mrz python3[985878]:   File "/root/kia-marzban-admin/utils/login.py", line 24, in login
Feb 18 09:13:44 mrz python3[985878]:     response = requests.post(url=login_url, data=data)
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 115, in post
Feb 18 09:13:44 mrz python3[985878]:     return request("post", url, data=data, json=json, **kwargs)
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 59, in request
Feb 18 09:13:44 mrz python3[985878]:     return session.request(method=method, url=url, **kwargs)
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 589, in request
Feb 18 09:13:44 mrz python3[985878]:     resp = self.send(prep, **send_kwargs)
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 703, in send
Feb 18 09:13:44 mrz python3[985878]:     r = adapter.send(request, **kwargs)
Feb 18 09:13:44 mrz python3[985878]:   File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 517, in send
Feb 18 09:13:44 mrz python3[985878]:     raise SSLError(e, request=request)
Feb 18 09:13:44 mrz python3[985878]: requests.exceptions.SSLError: HTTPSConnectionPool(host='IP', port=443): Max retries exceeded with url: /api/admin/token (Caused by SSLError(SSLCertVerificationError("hostname 'IP' doesn't match 'sub.domain.com'")))
Feb 19 12:11:35 mrz systemd[1]: Stopping Kia Marzban Bot Service...
Feb 19 12:11:35 mrz systemd[1]: kiamarzbanbot.service: Succeeded.
Feb 19 12:11:35 mrz systemd[1]: Stopped Kia Marzban Bot Service.
Feb 19 12:17:09 mrz systemd[1]: Started Kia Marzban Bot Service.
Feb 19 12:17:37 mrz python3[1657344]: Task exception was never retrieved
Feb 19 12:17:37 mrz python3[1657344]: future: <Task finished name='Task-16' coro=<Dispatcher._process_polling_updates() done, defined at /usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py:407> exception=SSLError(MaxRetryError("HTTPSConnectionPool(host='sub.domain.com', port=443): Max retries exceeded with url: /api/admin/token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))"))>
Feb 19 12:17:37 mrz python3[1657344]: Traceback (most recent call last):
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 666, in urlopen
Feb 19 12:17:37 mrz python3[1657344]:     httplib_response = self._make_request(
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
Feb 19 12:17:37 mrz python3[1657344]:     self._validate_conn(conn)
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1001, in _validate_conn
Feb 19 12:17:37 mrz python3[1657344]:     conn.connect()
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 366, in connect
Feb 19 12:17:37 mrz python3[1657344]:     self.sock = ssl_wrap_socket(
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
Feb 19 12:17:37 mrz python3[1657344]:     return context.wrap_socket(sock, server_hostname=server_hostname)
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
Feb 19 12:17:37 mrz python3[1657344]:     return self.sslsocket_class._create(
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/lib/python3.8/ssl.py", line 1069, in _create
Feb 19 12:17:37 mrz python3[1657344]:     self.do_handshake()
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/lib/python3.8/ssl.py", line 1338, in do_handshake
Feb 19 12:17:37 mrz python3[1657344]:     self._sslobj.do_handshake()
Feb 19 12:17:37 mrz python3[1657344]: ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)
Feb 19 12:17:37 mrz python3[1657344]: During handling of the above exception, another exception occurred:
Feb 19 12:17:37 mrz python3[1657344]: Traceback (most recent call last):
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 486, in send
Feb 19 12:17:37 mrz python3[1657344]:     resp = conn.urlopen(
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 720, in urlopen
Feb 19 12:17:37 mrz python3[1657344]:     retries = retries.increment(
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
Feb 19 12:17:37 mrz python3[1657344]:     raise MaxRetryError(_pool, url, error or ResponseError(cause))
Feb 19 12:17:37 mrz python3[1657344]: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sub.domain.com', port=443): Max retries exceeded with url: /api/admin/token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
Feb 19 12:17:37 mrz python3[1657344]: During handling of the above exception, another exception occurred:
Feb 19 12:17:37 mrz python3[1657344]: Traceback (most recent call last):
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
Feb 19 12:17:37 mrz python3[1657344]:     for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
Feb 19 12:17:37 mrz python3[1657344]:     return await asyncio.gather(*tasks)
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 117, in notify
Feb 19 12:17:37 mrz python3[1657344]:     response = await handler_obj.handler(*args, **partial_data)
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
Feb 19 12:17:37 mrz python3[1657344]:     return await self.callback_query_handlers.notify(update.callback_query)
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 117, in notify
Feb 19 12:17:37 mrz python3[1657344]:     response = await handler_obj.handler(*args, **partial_data)
Feb 19 12:17:37 mrz python3[1657344]:   File "/root/kia-marzban-admin/handlers/template.py", line 55, in template_manage
Feb 19 12:17:37 mrz python3[1657344]:     template_list = get_templates()
Feb 19 12:17:37 mrz python3[1657344]:   File "/root/kia-marzban-admin/utils/panel.py", line 22, in get_templates
Feb 19 12:17:37 mrz python3[1657344]:     token = login(panel_username, panel_pass)
Feb 19 12:17:37 mrz python3[1657344]:   File "/root/kia-marzban-admin/utils/login.py", line 24, in login
Feb 19 12:17:37 mrz python3[1657344]:     response = requests.post(url=login_url, data=data)
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 115, in post
Feb 19 12:17:37 mrz python3[1657344]:     return request("post", url, data=data, json=json, **kwargs)
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 59, in request
Feb 19 12:17:37 mrz python3[1657344]:     return session.request(method=method, url=url, **kwargs)
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 589, in request
Feb 19 12:17:37 mrz python3[1657344]:     resp = self.send(prep, **send_kwargs)
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 703, in send
Feb 19 12:17:37 mrz python3[1657344]:     r = adapter.send(request, **kwargs)
Feb 19 12:17:37 mrz python3[1657344]:   File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 517, in send
Feb 19 12:17:37 mrz python3[1657344]:     raise SSLError(e, request=request)
Feb 19 12:17:37 mrz python3[1657344]: requests.exceptions.SSLError: HTTPSConnectionPool(host='sub.domain.com', port=443): Max retries exceeded with url: /api/admin/token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

**Comment by Hoseinkhalaj1** [comment]
سرور رو عوض کردم مشکل حل شد 
تشکر از ادمین
